# Generated by Django 4.2 on 2023-04-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jadwal',
            new_name='jadwalModels',
        ),
    ]
